package(default_visibility = ["//visibility:public"])

py_library(
    name = "cartpolev0",
    srcs = [
        "cartpolev0.py",
    ],
)

py_library(
    name = "airraidramv0",
    srcs = [
        "airraidramv0.py",
    ],
)

py_library(
    name = "fetchpickandplacev1",
    srcs = [
        "fetchpickandplacev1.py",
    ],
)

py_library(
    name = "invertedpendulumv2",
    srcs = [
        "invertedpendulumv2.py",
    ],
)

py_library(
    name = "antv2",
    srcs = [
        "antv2.py",
    ],
)

py_library(
    name = "hopperv2",
    srcs = [
        "hopperv2.py",
    ],
)

py_library(
    name = "humanoidv2",
    srcs = [
        "humanoidv2.py",
    ],
)

py_library(
    name = "walker2dv2",
    srcs = [
        "walker2dv2.py",
    ],
)

py_library(
    name = "halfcheetahv2",
    srcs = [
        "halfcheetahv2.py",
    ],
)

py_library(
    name = "reacherv2",
    srcs = [
        "reacherv2.py",
    ],
)

py_library(
    name = "figureeight",
    srcs = [
        "figureeight.py",
    ],
)
