load(
    "@rules_proto//proto:defs.bzl",
    "proto_library",
)

load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "shared_proto",
    srcs = ["shared.proto"],
    deps = [
    ],
)
