package(default_visibility = ["//visibility:public"])

py_library(
    name = "model_constants",
    srcs = [
        "model_constants.py",
        "//protos/activity:model_constants_py_proto",
    ],
    deps = [
        "//model/utils:dict_util",
    ],
)

py_library(
    name = "inputs",
    srcs = [
        "inputs.py",
    ],
    deps = [
        "//model/utils:dict_util",
    ],
)
